name: Keep my Duolingo streak

on:
  schedule:
    - cron: '0 9,22 * * *'
  workflow_dispatch:
    inputs:
      lessons:
        default: 1
        description: 'Number of lessons to be completed'
        required: false
        type: number

jobs:
  study:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun index.js
        env:
          DUOLINGO_JWT: ${{ secrets.DUOLINGO_JWT }}
          LESSONS: ${{ inputs.lessons || 1 }}
  delete-old-runs:
    runs-on: ubuntu-latest
    permissions:
        actions: write
        contents: read
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          keep_minimum_runs: 20
          retain_days: 30
